version = 0.1
[default.deploy.parameters]
stack_name = "support-ops-alert-analyzer-mst"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["MstAnalyzerFunction=://amazonaws.com"]
